# Example ESPHome Configuration (Refactored)

# 1. Ensure the C++ files (.h, .cpp) and Python files
#    (__init__.py, sensor.py, binary_sensor.py, text_sensor.py)
#    are placed inside your ESPHome configuration directory,
#    within a 'custom_components/r60abd1/' subdirectory.

esphome:
  name: _sleep_monitor
  # ... other esphome settings ...
  # No includes or custom_component lambda needed anymore for basic setup!

# Configure the UART bus used to connect to the radar
uart:
  id: uart_bus # Give the UART bus an ID
  tx_pin: GPIO1 # Adjust to your ESP's TX pin connected to Radar RX
  rx_pin: GPIO3 # Adjust to your ESP's RX pin connected to Radar TX
  baud_rate: 115200

# Configure the  component itself (using the name from __init__.py)
r60abd1:
  id: radar_hub # Give the main component an ID
  uart_id: uart_bus # Link it to the UART bus defined above

# Define the sensors provided BY the r60abd1 component
# These now use standard ESPHome platform configuration
sensor:
  - platform: r60abd1 # Platform name matches the component folder
    # Link each sensor to the hub using its ID
    id: radar_hub # This should match the hub ID above for all sensors from this component
    distance:
      name: "毫米波雷达 人体距离"
      # unit_of_measurement, icon, etc. are now defined in sensor.py
      # You can override them here if needed, e.g.:
      # icon: "mdi:map-marker-radius"
    motion_state:
      name: "毫米波雷达 运动状态码"
    body_movement:
      name: "毫米波雷达 体动幅度"
    heart_rate:
      name: "毫米波雷达 心率"
      filters: # Optional filters can still be applied here
        - range:
            min: 30.0
            max: 200.0
    respiration_rate:
      name: "毫米波雷达 呼吸率"
    sleep_score:
      name: "毫米波雷达 睡眠评分"
    position_x:
      name: "毫米波雷达 位置 X"
    position_y:
      name: "毫米波雷达 位置 Y"
    position_z:
      name: "毫米波雷达 位置 Z"

binary_sensor:
  - platform: r60abd1
    id: radar_hub # Link to the hub
    presence:
      name: "毫米波雷达 人体存在"
    bed_status:
      name: "毫米波雷达 在床状态"

text_sensor:
  - platform: r60abd1
    id: radar_hub # Link to the hub
    motion_text:
      name: "毫米波雷达 运动状态"
    respiration_info:
      name: "毫米波雷达 呼吸信息"
    sleep_stage:
      name: "毫米波雷达 睡眠阶段"

# --- Future: Add switches, numbers, selects here ---
# switch:
#   - platform: r60abd1
#     id: radar_hub
#     # Example: Define a switch based on switch.py config
#     presence_detection_switch: # Assuming you define this key in switch.py
#       name: "Enable Presence Detection"
#
# number:
#   - platform: r60abd1
#     id: radar_hub
#     # Example: Define a number based on number.py config
#     unattended_timer: # Assuming you define this key in number.py
#       name: "Unattended Timer Setting"
#       min_value: 30
#       max_value: 180
#       step: 10
#       unit_of_measurement: "min"

