pacakage:
  core: !include mmwave-r60abd1-esp32s3.yaml

esphome:
  project:
    name: zomco.mmwave-r60abd1
    version: dev

# Configure the UART bus
uart:
  id: uart_bus
  tx_pin: GPIO14
  rx_pin: GPIO13
  baud_rate: 115200
  debug:

# Configure the component hub
r60abd1:
  id: radar_hub
  uart_id: uart_bus

# Configure Sensors
sensor:
  - platform: r60abd1 
    distance:
      name: "Distance"
    body_movement:
      name: "Body Movement"
    heart_rate:
      name: "Heart Rate"
    respiration_rate:
      name: "Respiration Rate"
    sleep_score:
      name: "Sleep Score"
    position_x:
      name: "Position X"
    position_y:
      name: "Position Y"
    position_z:
      name: "Position Z"
    heart_rate_waveform_pt0:
      name: "Heart Rate Waveform Point0"
    heart_rate_waveform_pt1:
      name: "Heart Rate Waveform Point1"
    heart_rate_waveform_pt2:
      name: "Heart Rate Waveform Point2"
    heart_rate_waveform_pt3:
      name: "Heart Rate Waveform Point3"
    heart_rate_waveform_pt4:
      name: "Heart Rate Waveform Point4"
    respiration_waveform_pt0:
      name: "Respiration Waveform Point0"
    respiration_waveform_pt1:
      name: "Respiration Waveform Point1"
    respiration_waveform_pt2:
      name: "Respiration Waveform Point2"
    respiration_waveform_pt3:
      name: "Respiration Waveform Point3"
    respiration_waveform_pt4:
      name: "Respiration Waveform Point4"

# Configure Binary Sensors
binary_sensor:
  - platform: r60abd1
    presence:
      name: "Presence"
    bed_status:
      name: "Bed Status"

# Configure Text Sensors
text_sensor:
  - platform: r60abd1
    motion_info:
      name: "Motion Info"
    respiration_info:
      name: "Respiration Info"
    sleep_stage:
      name: "Sleep Stage"
    firmware_version:
      name: "Firmware Version"
    sleep_rating:
      name: "Sleep Rating"

# --- Configure Control Entities ---

# Configure Switches
switch:
  - platform: r60abd1
    presence_detection:
      name: "Presence Detection"
    heart_rate_detection:
      name: "Heart Rate Detection"
    respiration_detection:
      name: "Respiration Detection"
    sleep_monitoring:
      name: "Sleep Monitoring"
    heart_rate_waveform:
      name: "Heart Rate Waveform"
    respiration_waveform:
      name: "Respiration Waveform"
    struggle_detection:
      name: "Struggle Detection"
    unattended_detection:
      name: "Unattended Detection"

# Configure Numbers
number:
  - platform: r60abd1
    respiration_low_threshold:
      name: "Respiration Low Threshold"
    unattended_time:
      name: "Unattended Time"
    sleep_end_time:
      name: "Sleep End Time"

# Configure Selects
select:
  - platform: r60abd1
    struggle_sensitivity:
      name: "Struggle Sensitivity"