name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - mmwave-r60abd1-esp32s3

        esphome-version:
          - stable
          - beta
          - dev
  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5.0.0
      - name: ESPHome Stable
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
