name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.1.0
    with:
      files: |
        r60abd1-esp32s3.factory.yaml
      esphome-version: 2024.12.2
      combined-name: mmwave

      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.1.0
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}
