esphome:
  name: r60abd1-test
  friendly_name: r60abd1-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: "LYHkgt5qazHFNSg89qBMsaz5tbs8ZMl0t5hf7O8b2Wc="

ota:
  - platform: esphome
    password: "2205f57147923abb900acec9ebdc15d3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "R60Abd1-Test Fallback Hotspot"
    password: "cK3YzXWehtza"

captive_portal:

external_components:
  - source:
      type: local
      path: mmwave
    components: r60abd1
  
# Configure the UART bus
uart:
  id: uart_bus
  tx_pin: GPIO14
  rx_pin: GPIO13
  baud_rate: 115200
  debug:

# Configure the component hub
r60abd1:
  id: radar_hub
  uart_id: uart_bus

# Configure Sensors
sensor:
  - platform: r60abd1 
    distance:
      name: "Distance"
    body_movement:
      name: "Body Movement"
    heart_rate:
      name: "Heart Rate"
    respiration_rate:
      name: "Respiration Rate"
    sleep_score:
      name: "Sleep Score"
    position_x:
      name: "Position X"
    position_y:
      name: "Position Y"
    position_z:
      name: "Position Z"
    heart_rate_waveform_pt0:
      name: "Heart Rate Waveform Point0"
    heart_rate_waveform_pt1:
      name: "Heart Rate Waveform Point1"
    heart_rate_waveform_pt2:
      name: "Heart Rate Waveform Point2"
    heart_rate_waveform_pt3:
      name: "Heart Rate Waveform Point3"
    heart_rate_waveform_pt4:
      name: "Heart Rate Waveform Point4"
    respiration_waveform_pt0:
      name: "Respiration Waveform Point0"
    respiration_waveform_pt1:
      name: "Respiration Waveform Point1"
    respiration_waveform_pt2:
      name: "Respiration Waveform Point2"
    respiration_waveform_pt3:
      name: "Respiration Waveform Point3"
    respiration_waveform_pt4:
      name: "Respiration Waveform Point4"

# Configure Binary Sensors
binary_sensor:
  - platform: r60abd1
    presence:
      name: "Presence"
    bed_status:
      name: "Bed Status"

# Configure Text Sensors
text_sensor:
  - platform: r60abd1
    motion_info:
      name: "Motion Info" # 无, 静止, 活跃
    respiration_info:
      name: "Respiration Info" # 正常, 过高, 过低, 无
    sleep_stage:
      name: "Sleep Stage" # 深睡, 浅睡, 清醒, 无
    firmware_version:
      name: "Firmware Version" # 显示雷达的固件版本号
    sleep_rating:
      name: "Sleep Rating" # 显示睡眠评分

# --- Configure Control Entities ---

# Configure Switches
switch:
  - platform: r60abd1
    presence_detection:
      name: "Presence Detection"
    heart_rate_detection:
      name: "Heart Rate Detection"
    respiration_detection:
      name: "Respiration Detection"
    sleep_monitoring:
      name: "Sleep Monitoring"
    heart_rate_waveform:
      name: "Heart Rate Waveform"
    respiration_waveform:
      name: "Respiration Waveform"
    struggle_detection:
      name: "Struggle Detection"
    unattended_detection:
      name: "Unattended Detection"

# Configure Numbers
number:
  - platform: r60abd1
    respiration_low_threshold:
      name: "Respiration Low Threshold" # 设置呼吸率低于多少时报告“过低”
      # min/max/step 在 number.py 中定义 (10-20 rpm, step 1)
    unattended_time:
      name: "Unattended Time" # 设置无人多久后触发“无人计时异常”
      # min/max/step 在 number.py 中定义 (30-180 min, step 10)
    sleep_end_time:
      name: "Sleep End Time" # 设置离床多久后判断睡眠结束
      # min/max/step 在 number.py 中定义 (5-120 min, step 1)

# Configure Selects
select:
  - platform: r60abd1
    struggle_sensitivity:
      name: "Struggle Sensitivity"